create table if not exists public.articles (
  id bigint generated by default as identity primary key,
  url_original text,
  final_url text,
  canonical_url text,
  title text,
  source text,
  published_at text,
  fetched_at text,
  domain text,
  link_status text,
  verification_note text,
  unique (canonical_url),
  unique (final_url)
);

create table if not exists public.daily_briefs (
  id bigint generated by default as identity primary key,
  date text not null,
  mode text not null,
  level text not null,
  json text not null,
  created_at text not null,
  unique (date, mode, level)
);

create index if not exists idx_daily_briefs_lookup
  on public.daily_briefs (date, mode, level);
